### ISSUE TITLE
Error: BAD uri lacks scheme, falling back to file-scheme.

### ISSUE THREAD

**Issue by vfonic** [fabiospampinato/vscode-projects-plus#39]
I'm getting the following errors in DEBUG CONSOLE.

I only see this when I Start Debugging an extension.
When I Start Debugging a web app, I don't see the error.

<details><summary>Trace log</summary>
Trace: BAD uri lacks scheme, falling back to file-scheme.
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:120:484
	at new f (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:120:557)
	at new p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:122:808)
	at Function.parse (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:122:157)
	at Object.getProjectByPath (/Users/viktor/.vscode/extensions/fabiospampinato.vscode-projects-plus-1.22.0/out/extension.js:9:81819)
	at Object.updateVariables (/Users/viktor/.vscode/extensions/fabiospampinato.vscode-projects-plus-1.22.0/out/extension.js:9:105238)
	at Object.update (/Users/viktor/.vscode/extensions/fabiospampinato.vscode-projects-plus-1.22.0/out/extension.js:9:105003)</details>

**Comment by fabiospampinato** [comment]
It seems to be a problem related to updating the statusbar item https://github.com/fabiospampinato/vscode-projects-plus/blob/ac34b7537f377cae54e7b889470a0e92d6ba2e38/src/statusbar.ts#L93-L99. 

I'm not sure why this is happening.
